version: "3.7"
services:
  web_store:
    container_name: web_store
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:443"
    volumes:
      - "./web/www/:/var/www/html"
    networks:
      - store
    restart: unless-stopped
    depends_on:
      - db_store

  db_store:
    container_name: db_store
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
      MYSQL_DATABASE: store
      MYSQL_USER: web
      MYSQL_PASSWORD: P@ssw0rd!
    volumes:
      - "./database/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      - store
    restart: unless-stopped

networks:
  store:
    driver: bridge
